accounts/api/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin

from .views import (
    UserCreateAPIView,
    UserLoginAPIView
    )

# urlpatterns = [
#     path(r'^$', CommentListAPIView.as_view(), name='list'),
#     path(r'^create/$', CommentCreateAPIView.as_view(), name='create'),
#     path(r'^(?P<pk>\d+)/$', CommentDetailAPIView.as_view(), name='thread'),
#     # url(r'^(?P<id>\d+)/delete/$', comment_delete, name='delete'),
# ]
#
# app_name = 'organization'


urlpatterns = [
    path('login/', UserLoginAPIView.as_view(), name='login'),
    path('register/', UserCreateAPIView.as_view(), name='register'),
]

accounts/urls.py
from django.urls import path

from .views import (
    Profile,
    user_create,
    )


app_name = 'accounts'
urlpatterns = [
    # ex: /polls/
    path('',  Profile, name='Profile'),
    path('create/', user_create, name='user_create'),

    # path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    # path(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    # path(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

apps/employee/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin

# from .views import (
#     # UserCreateAPIView,
#     # UserLoginAPIView
#     )


from . import views


app_name = 'employee'
urlpatterns = [
    # ex: /polls/
    path('',  views.index, name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

opcms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('apps.dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('employee/', include('apps.employee.urls')),
    # path('organization/', include('apps.organization.urls')),


    #
    # path('api/organization/', include('apps.organization.api.urls')),
    # path('api/users/', include('apps.accounts.api.urls')),
    # path('polls/', include('polls.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import (
        BaseUserManager,
        AbstractBaseUser,
        PermissionsMixin,
        AbstractUser
    )
# from django.contrib.auth.models import PermissionsMixin
# Create your models here.
# Person

# from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _


import re
from django import forms
from django.core.exceptions import ValidationError


def mobile_validate(value):
    mobile_re = re.compile(r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57])[0-9]{8}$')
    if not mobile_re.match(value):
        raise ValidationError('手机号码格式错误')


class OpUserManager(BaseUserManager):
    def create_user(self, username, mobile, identification, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not mobile:
            raise ValueError('Users must have an mobile address')

        user = self.model(
            username=username,
            mobile=mobile,
            identification=identification,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, mobile, identification, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username,
            mobile,
            identification,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Opuser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_("用户名"), max_length=255, unique=True)
    identification = models.CharField(_("身份证号"), max_length=100, unique=True)
    mobile = models.CharField(_("手机"),
                              validators=[mobile_validate,],
                              error_messages={'required':u'手机不能为空'} ,
                              max_length=12,
                              unique=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = OpUserManager()

    USERNAME_FIELD = 'mobile'
    # USERNAME_FIELD = 'name'
    REQUIRED_FIELDS = ('username', 'identification',)

    def __str__(self):
        return self.username

    # def has_perm(self, perm, obj=None):
    #     "Does the user have a specific permission?"
    #     # Simplest possible answer: Yes, always
    #     return True
    #
    # def has_module_perms(self, app_label):
    #     "Does the user have permissions to view the app `app_label`?"
    #     # Simplest possible answer: Yes, always
    #     return True



class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # identification = models.CharField(max_length=100)
    # email = models.EmailField(max_length=255,unique=True)
    # avatar = models.ImageField(_("证件照"), upload_to=avatar_file_name, blank=True)

    def __str__(self):
        return str(self.user.username)

accounts/forms.py
from django import forms

# from pagedown.widgets import PagedownWidget

from .models import Opuser


class RegisterForm(forms.Form):
    username = forms.CharField()
    identification = forms.CharField()
    mobile = forms.CharField()
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        if len(password1) <= 4:
            raise forms.ValidationError("Password is too short")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get("username")

        username_qs = Opuser.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        return username
        # try:
        #     exists = Opuser.objects.get(username=username)
        #     raise forms.ValidationError("This username is taken")
        # except Opuser.DoesNotExist:
        #     return username
        # except:
        #     raise forms.ValidationError("There was an error, please try again or contact us.")

    #
    def clean_identification(self):
        identification = self.cleaned_data.get("identification")
        identification_qs = Opuser.objects.filter(identification=identification)
        if identification_qs.exists():
            raise forms.ValidationError("This identification has already been registered")
        return identification


    def clean_mobile(self):
        mobile = self.cleaned_data.get("mobile")
        mobile_qs = Opuser.objects.filter(mobile=mobile)
        if mobile_qs.exists():
            raise forms.ValidationError("This mobile has already been registered")
        return mobile

accounts/api/views.py
from django.db.models import Q
from django.contrib.auth import get_user_model

from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)

from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView
)
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,

)

# from posts.api.permissions import IsOwnerOrReadOnly
# from posts.api.pagination import PostLimitOffsetPagination, PostPageNumberPagination

User = get_user_model()

from .serializers import (
    UserCreateSerializer,
    UserLoginSerializer,
)


class UserCreateAPIView(CreateAPIView):
    serializer_class = UserCreateSerializer
    queryset = User.objects.all()
    permission_classes = [AllowAny]


class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

accounts/views.py
from django.contrib.auth.decorators import login_required
# from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse


from .models import Opuser
from .forms import RegisterForm
# Create your views here.



def Profile(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': 12}
    return render(request, 'accounts/profile.html', context)


# @login_required
def user_create(request):

#     if not request.user.is_staff or not request.user.is_superuser:
#         raise Http404

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        identification = form.cleaned_data['identification']
        mobile = form.cleaned_data['mobile']
        password = form.cleaned_data['password2']
        # MyUser.objects.create_user(username=username, email=email, password=password)
        new_user = Opuser()
        new_user.username = username
        new_user.mobile = mobile
        new_user.identification = identification
        new_user.set_password(password)  # RIGHT
        new_user.save()

    action_url = reverse("accounts:user_create")
    title = "accounts"
    submit_btn = "Create free account"

    context = {
        "form": form,
        "action_url": action_url,
        "title": title,
        "submit_btn": submit_btn
    }
    return render(request, "accounts/user_create.html", context)

accounts/templates/accounts/index11.html
{% extends "base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo;
&rsaquo; {% trans 'Bookmarklets' %}
</div>
{% endblock %}
{% block title %}{% trans "Documentation bookmarklets" %}{% endblock %}

{% block content %}

<p class="help">{% blocktrans trimmed %}
To install bookmarklets, drag the link to your bookmarks toolbar, or right-click
the link and add it to your bookmarks. Now you can select the bookmarklet
from any page in the site.
{% endblocktrans %}</p>

<div id="content-main">
   <p>{% trans "0000Jumps you from any page to the documentation for the view that generates that page." %}</p>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/opcms.css" %}" />
{% endblock %}

{% block bodyclass %}{{ block.super }}dashboard{% endblock %}
{% block coltype %}colSM{% endblock %}


{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'accounts:index' %}">{% trans 'Home' %}</a>
&rsaquo; Bookmarklets
&rsaquo; Bookmarklet
</div>
{% endblock %}


{% block content %}
<div id="content-main">
asdada

</div>{% endblock %}


{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>我的工作</h2>
        <h3>{% trans 'My actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br/>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type }}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user_create.html
{% extends "base_site.html" %}





{% block bodyclass %}{{ block.super }}dashboard{% endblock %}
{% block coltype %}colSM{% endblock %}

{% block content %}
<div id="content-main">

<form method='POST' action='{{ action_url }}'>{% csrf_token %}

  <fieldset class="module aligned ">
        <div class="form-row field-user">
            <table>
                {{ form.as_table  }}
            </table>
        </div>
  </fieldset>

<input class='btn btn-default {{ submit_btn_class }}' type='submit' value='{{ submit_btn }}'/>

</form>


{% if extra_form_link %}
<br/>
<p>
{{ extra_form_link|safe }}
</p>
{% endif %}


{% if title == "Login" %}
<br/>
<p>
Need Account?>Register now.
</p>
{% endif %}

</div>
{% endblock %}