apps/dashboard/urls.py
from django.urls import path

from . import views


app_name = 'dashboard'
urlpatterns = [
    # ex: /polls/
    path('',  views.index, name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

apps/employee/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib import admin

# from .views import (
#     # UserCreateAPIView,
#     # UserLoginAPIView
#     )


from . import views


app_name = 'employee'
urlpatterns = [
    # ex: /polls/
    path('',  views.index, name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

opcms/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('', include('apps.dashboard.urls')),
    path('accounts/', include('accounts.urls')),
    path('employee/', include('apps.employee.urls')),
    # path('organization/', include('apps.organization.urls')),


    #
    # path('api/organization/', include('apps.organization.api.urls')),
    # path('api/users/', include('apps.accounts.api.urls')),
    # path('polls/', include('polls.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opcms/templates/base_site.html
{% extends "admin/base.html" %}
{% load i18n static %}

{% block title %}{{ title }} | {{ site_title|default:_('OpCMS') }}{% endblock %}

{% block branding %}
<img src="{% static "css/img/white-opcms.svg" %}" width="141" height="40" alt="">
<!--<h1 id="site-name"><a href="{% url 'dashboard:index' %}">{{ site_header|default:_('OPCMS') }}</a></h1>-->
{% endblock %}

{% block nav-global %}{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'dashboard:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'employee:index' %}">人力资源</a>
&rsaquo; <a href="/#">固定资产</a>
</div>
{% endblock %}